### ISSUE TITLE
Duplicated client not closing correctly

### ISSUE THREAD

**Issue by iiegor** [iiegor/xat-server#16]
## Preview

![img](https://drive.google.com/uc?export=download&id=0B9WchF8WhEn9RVNZMkZvbjFiajg)
## Details

This issue appeared since the introduction of c2f440740fcbeef86703f326fc85ade2443a1a43.
Probably related with [handler.coffee#L64](https://github.com/iiegor/xat-server/blob/master/src/services/handler.coffee#L64) and [server.coffee#L39](https://github.com/iiegor/xat-server/blob/master/src/services/server.coffee#L39).

**Comment by huumanoid** [comment]
This happens because disconnection of duplicated client handles after j2 dispatching.

Look:
Let's say we are using profile with id 123
1. Connecting first time
What is going on when we are connecting second time?
2. j2 dispatching
2.1 User.process
2.2 then:
   here we raising socket.end() event and setting global.Server.clients[123] = newhandler
2.3 Chat.joinRoom
3. socket.on 'end' in server.coffee
here we perform delete @clients[client.id] where client.id is 123

so what do we have? there is no 123 user in clients array.

The way to fix: set client.id to dummy value after raising socket.end(). for ex.: client.id = -(1<<31)

Looks.. bad. But works.

**Comment by huumanoid** [comment]
check out the other, better way to fix it. 
huumanoid/xat-server@4cf61cdbd43dbc8319ab7477b7cb4a9484f81d29
it's better because fix other two bugs related with dup handling.

**Comment by iiegor** [comment]
Hey @HuuMaNoID, thanks for the info, I solved this by another way (see on branch [improve/client-management](https://github.com/iiegor/xat-server/tree/improve/client-management)), what do you think?

**Comment by huumanoid** [comment]
Your solution looks OK.
